### PR TITLE
chore: fixed gosec

### PR DESCRIPTION
**Pull request by renanbastos93**
```
[C:\Users\Unknow\Desktop\git\proxy\main.go:133] - 
    G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
        > Forward(c, target)
```

### CODE REVIEW

**Comment by thomasvvugt** [comment]
Looks good, we'd have to wait for Fenny to merge this, though.
It seems some repositories aren't listed under our maintainers team.
Thanks @renanbastos93 🎉!

**Comment by renanbastos93** [comment]
> Maybe we should call the new error handler here, `c.Next(err)`

@Fenny 
seems a fine idea, sorry I didn't remember this approach to use Next. So I believe that we must respect the method Forward cuz made a send status, in this case, we should close the flow.

**Comment by Fenny** [comment]
@renanbastos93 calling `c.Next(err)` will default to a `500 Internal Server Error`, but we provide the possibility to create a custom error handler if the user wants to return a different error: https://docs.gofiber.io/error-handling

**Comment by renanbastos93** [comment]
> @renanbastos93 calling `c.Next(err)` will default to a `500 Internal Server Error`, but we provide the possibility to create a custom error handler if the user wants to return a different error: https://docs.gofiber.io/error-handling

@Fenny Shouldn't remove currently log, as we go to use the Next(err)?

**Pull request merged**
